# 3. Запустить скрипт, без "docker build" и "docker run", запустить docker compose (сделать в нём docker build и docker run)

version: '3.9'

services:
  server:
    build: C:\Users\Home\IdeaProjects\working\Docker\Server
    ports:
      - '8081:8081'
    networks:
      - server-client

  client:
    build: C:\Users\Home\IdeaProjects\working\Docker\Client
    ports:
      - '8080:8080'
    environment:
      - SERVER_URL=http://server:8081
    networks:
      - server-client

networks:
  server-client:
    driver: bridge